url: https://y7kim.github.io
baseurl: ""

# Site settings
title: TEAM Janine
email: info@teamjanine.de
description: "Work.Out.Door, Personal training, Lauf Mama lauf, athletic balance"


# Team names, titles and social links
teamlead-name: Dein Coach Janine
teamlead-pic: janine
teamlead-slogan: "Korrekturfreak mit #jihaa"
teamlead-description: "Janine Wilhelm steht hinter TEAM Janine. Wenn Herzblut gepaart mit positiver Energie auf Feuer im Popo und fitte Mitte trifft. Ihre Ausbildungen passen auf keine DIN A 4 Seite. Sie ist zertifizierte <b>Functional & Personal Trainerin</b>, <b>DeepWORK® BODYART® Coach</b>, <b>3 D Rücken Instructor</b>, <b>Prä-und postpartale Gesundheitstrainerin mit Spezialisierung Rectus diastase und Kursleiterin Beckenbodengymnastik §20 + 20a SGB</b>. Und sie leitet als Dozentin das Modul funktionelles <b>Beckenbodentraining für die Sporttherapeuten</b> sowie die <b>Beckenbodenausbildungen für LAUFMAMALAUF</b>." 
teamlead-motto: "Ihr Motto: Nice & slow bei der Übungsausführung und quick & dirty in der Kommunikation."
teamlead-social: 
    - title: instagram
      url: https://www.instagram.com/team_janine_kirchheim/   

people:
- name: Catrin
  pic: catrin
  slogan: "Dancing queen mit Ausstrahlung"
  description: "Hot like hell, den Hintern im Griff beim tanzen, unfassbar positiv, ein umwerfendes Lächeln und on top mit ordentlich Bums in den Workouts. Sie rockt die Weilheimer Freitagskurse und hinterlässt Spuren, damit jeder noch am Wochenende an sie denken wird."
  social:
    - title: twitter
      url: #

- name: Simone
  pic: simone
  slogan: Yogamaster mit Sonne im Herzen
  description: "Voll im Flow mit ruhiger und kraftvoller Dynamik bringt sie alle zum glitzern und jeden in seine Mitte. Die Stunde vergeht wie im Flug und Mobilisierung kennt keine Grenzen."
  social:
    - title: instagram
      url: #

- name: Silke
  pic: silke
  slogan: "Deepworkrakete mit viel Empathie"
  description: "Und wenn du denkst, tiefer gehts nicht mehr...doch, bei Silke schon. Definitiiieeef tiefer. Völlig unaufgeregt wirst du in deiner Technik unbemerkt korrigiert und mit einem flott frechen Spruch zum weitermachen motiviert."
  social:
    - title: instagram
      url: #

- name: Vanessa
  pic: vanessa
  slogan: Kreativer Kopf mit Charme
  description: Die kreative unter uns Raketen, die die Anstrengung im Kurs beim Bingo spielen mit einem charmanten Lächeln wegzaubert und direkt schon wieder die nächste Idee im Kopf hat. 
  social:
    - title: instagram
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/team_janine_kirchheim/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty